language: generic

services:
  - docker

jobs:
  include:
    - stage: test
      script:
        - ls
        - docker build -f ./Dockerfile.test -t attainia/wkhtmltox-api-test .
        - docker run wkhtmltox-api-test go test -v wkhtmltox-api/cmd
        - docker run wkhtmltox-api-test go test -v wkhtmltox-api/internal

deploy:
  provider: script
  script: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t docker build -t attainia/wkhtmltox-api .
          docker push attainia/wkhtmltox-api
  on:
    branch: master
